name: Build EXE

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Compile Java
        run: javac InventoryApp.java

      - name: Create JAR
        run: jar cfe InventoryApp.jar InventoryApp InventoryApp.class

      - name: Generate EXE
        run: |
          jpackage `
          --input . `
          --name InventoryApp `
          --main-jar InventoryApp.jar `
          --main-class InventoryApp `
          --type exe

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: InventoryApp-EXE
          path: "*.exe"
